version: "3"

services:
  hugo:
    container_name: hugo_theme_iris
    # image: "peaceiris/hugo:v${HUGO_VERSION}"
    image: peaceiris/hugo:v${HUGO_VERSION}-mod # Hugo Modules
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src/hugo-theme-iris
    stdin_open: true
    tty: true
    working_dir: /src/hugo-theme-iris/exampleSite
    command:
      - server
      - --navigateToChanged
      - --bind=0.0.0.0
      - --buildDrafts
      - --themesDir
      - ../../
      - --i18n-warnings
